export const thanksList = {
  groupList: ['XivStrat', 'MMW', 'MGL', 'SuperJump'],
  devList: [
    'SuperJump',
    'Hikaru',
    'DavidKitano',
    'BaiXi',
    'LuoLuoKe',
    'TiramisuE',
    'Ling',
    'Saleri',
    'Demon',
    'Javsen',
    'DaGongYou',
    'NaiSeR',
    'YouChai',
    'CongYun',
    'YuKa',
  ],
  other: [],
}
